spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.9.221.111:12345/study?userSSL=false
    username: root
    password: hl951103

  redis:
    host: 139.9.221.111
    port: 6379
    password: TheRuffian945
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 30000
server:
  port: 10086
logging:
  level:
    root: info
    com.example: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl